substitutions:
  uart_tx_pin: GPIO3
  uart_rx_pin: GPIO4

packages:
  acr_pa_v1: !include acr-pa.yaml

dashboard_import:
  package_import_url: github://Senhus-DK/senhus-connect-esphome/acr-pa-v2.yaml@main
